export default {
  BAD_APPLICATION: 'BAD_APPLICATION',
  BAD_DATA: 'BAD_DATA',
  BAD_ORGANIZATION: 'BAD_ORGANIZATION',
  MISSING_PASSWORDS: 'MISSING_PASSWORDS',
  NO_USER: 'NO_USER',
  PASSWORD_MISMATCH: 'PASSWORD_MISMATCH'
}
