export default {
  BAD_APPLICATION: 'BAD_APPLICATION',
  BAD_DATA: 'BAD_DATA',
  BAD_ORGANIZATION: 'BAD_ORGANIZATION',
  MISSING_APPLICATIONID: 'MISSING_APPLICATIONID',
  MISSING_APPLICATIONSECRET: 'MISSING_APPLICATIONSECRET',
  MISSING_EMAIL: 'MISSING_EMAIL',
  MISSING_PASSWORD: 'MISSING_PASSWORD',
  MISSING_PASSWORDS: 'MISSING_PASSWORDS',
  MISSING_USERNAME: 'MISSING_USERNAME',
  NO_USER: 'NO_USER',
  PASSWORD_MISMATCH: 'PASSWORD_MISMATCH'
}
